### ISSUE TITLE
Dragging Fails when Placed in a Modal

### ISSUE THREAD

**Issue by jzumbrun** [WickyNilliams/react-simple-colorpicker#17]
First thanks for the smaller code base. Many npm projects are grossly bloated.

If I place ColorPicker on the page it works fine. However if I place it a modal, meaning its original location was say close to the top of the page but due to ColorPicker being a child of a modal, when the modal opens the position of the ColorPicker is now different than its initial location, the dragging fails.
Usually it does not move. If the modal has a vertical scroll and I can get the position of the ColorPicker close to its original position via the modals scroll bars, then the dragging works again. This happens with the map and the sliders, I am assuming that something in DraggableMixin must be reset if the position changes from its original.

**Comment by WickyNilliams** [comment]
Can you create a fiddle or similar to demonstrate the issue?

**Comment by jzumbrun** [comment]
Got a "failing" fiddle here:
https://jsfiddle.net/jzumbrun/69z2wepo/52334/

**Comment by WickyNilliams** [comment]
Fixed, and published to npm as `v1.4.1`

**Comment by WickyNilliams** [comment]
Here's your fiddle with the latest version. Works perfectly 👍 

https://jsfiddle.net/jzumbrun/69z2wepo/52334/
