### ISSUE TITLE
React 15.5.0 deprecations

### ISSUE THREAD

**Issue by albertogasparin** [WickyNilliams/react-simple-colorpicker#21]
`React.createClass` and `React.PropTypes` access [is now deprecated](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html). 
It would be great to take the opportunity to move to ES6 classes too.

**Comment by chenop** [comment]
@WickyNilliams 
Hi, thanks for creating this package we are using it!
I am willing to handle this issue - Are you still maintaining this package?
will you accept my PR once done?

**Comment by WickyNilliams** [comment]
I'm still maintaining, but I've been slacking a little recently. However there's already an open PR for this: #24. Currently on vacation will merge when I return

**Comment by chenop** [comment]
Ok, thanks

**Comment by WickyNilliams** [comment]
Published to npm as `v1.4.2`

**Comment by chenop** [comment]
Errors are gone, thanks for merging this release.
