### ISSUE TITLE
react as dependency breaks projects using react/addons

### ISSUE THREAD

**Issue by BradHarris** [WickyNilliams/react-simple-colorpicker#9]
When `react-simple-colorpicker` is required by a project that uses `react/addons`, both `react` and `react/addons` get included and they clobber each other.

**Comment by WickyNilliams** [comment]
Thanks Brad. Will try to get this done tonight, if not, tomorrow (PRs welcome ;)

**Comment by magnusohlin** [comment]
Any news on this one? It breaks my app as well.

**Comment by WickyNilliams** [comment]
Crap, I thought I had pushed the fix for this already! It's done and waiting to be released, along with a bunch of performance fixes. Will release some time over the weekend and report back here

**Comment by magnusohlin** [comment]
@WickyNilliams How did it go? Do you need help with anything?

**Comment by WickyNilliams** [comment]
Fixed in 3458f292c43aada030606991e68d865751df6b69
